import type { Store } from '@yourorg/store-engine';

export const sampleStore: Store = {
  id: 'demo-store-001',
  name: 'Urban Essentials',
  slug: 'urban-essentials',
  description: 'Curated modern lifestyle products',
  config: {
    theme: 'light',
    currency: 'USD',
    locale: 'en',
  },
  pages: [
    {
      id: 'page-home',
      slug: 'home',
      title: 'Home',
      layout: {
        type: 'grid',
        props: {},
        children: [
          { type: 'store-header', props: {}, key: 'header' },
          {
            type: 'column',
            props: { lg: 16 },
            key: 'hero',
            children: [
              {
                type: 'hero-banner',
                props: {
                  fullWidth: true,
                  title: 'Urban Essentials',
                  subtitle: 'Curated products for modern living',
                },
                key: 'hero-banner',
              },
            ],
          },
          {
            type: 'column',
            props: { lg: 16 },
            key: 'catalog',
            children: [
              { type: 'product-grid', props: { columns: 3 }, key: 'products' },
            ],
          },
          { type: 'store-footer', props: {}, key: 'footer' },
        ],
      },
    },
  ],
  products: [
    {
      id: 'p1',
      name: 'Minimalist Backpack',
      description: 'Clean-line daypack in waterproof canvas. Fits a 15" laptop with room for essentials.',
      price: 89.0,
      currency: 'USD',
      images: [],
      category: 'bags',
      tags: ['backpack', 'minimalist'],
      variants: [],
      inStock: true,
    },
    {
      id: 'p2',
      name: 'Ceramic Pour-Over Set',
      description: 'Hand-thrown ceramic dripper and carafe. Brew better coffee at home.',
      price: 54.0,
      currency: 'USD',
      images: [],
      category: 'kitchen',
      tags: ['coffee', 'ceramic'],
      variants: [],
      inStock: true,
    },
    {
      id: 'p3',
      name: 'Merino Wool Beanie',
      description: 'Ultra-soft merino knit. Naturally temperature-regulating.',
      price: 38.0,
      currency: 'USD',
      images: [],
      category: 'apparel',
      tags: ['beanie', 'wool'],
      variants: [
        { id: 'v1', name: 'Charcoal' },
        { id: 'v2', name: 'Oatmeal' },
        { id: 'v3', name: 'Forest' },
      ],
      inStock: true,
    },
    {
      id: 'p4',
      name: 'Brass Desk Lamp',
      description: 'Adjustable arm with warm-tone LED. Solid brass finish that patinas over time.',
      price: 125.0,
      currency: 'USD',
      images: [],
      category: 'lighting',
      tags: ['lamp', 'brass', 'desk'],
      variants: [],
      inStock: true,
    },
    {
      id: 'p5',
      name: 'Linen Notebook',
      description: 'Cloth-bound A5 journal with 192 dot-grid pages.',
      price: 22.0,
      currency: 'USD',
      images: [],
      category: 'stationery',
      tags: ['notebook', 'linen'],
      variants: [],
      inStock: true,
    },
    {
      id: 'p6',
      name: 'Cork Yoga Block',
      description: 'Sustainable natural cork. Non-slip grip with beveled edges.',
      price: 28.0,
      currency: 'USD',
      images: [],
      category: 'fitness',
      tags: ['yoga', 'cork'],
      variants: [],
      inStock: true,
    },
  ],
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};
